//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderHeaderShipping
    {
        public int SalesOrderID { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<int> ShipToAddressID { get; set; }
        public Nullable<int> ShipMethod { get; set; }
    }
}
